### ISSUE TITLE
Module Not Compatible with terraform-google-provider v2.0.0

### ISSUE THREAD

**Issue by TaysirTayyab** [GoogleCloudPlatform/terraform-google-nat-gateway#110]
Well it finally happened. All those deprecated resources finally got tossed with the Feb 12 with the 2.0 release of the terraform google provider.

```
Error: module.nat_gateway_zone1.module.nat-gateway.google_compute_instance_template.default: "network_interface.0.address": [REMOVED] Please use network_ip
```

**Comment by cloud-rocket** [comment]
Anything new with this?

**Comment by mackoftrack** [comment]
Bump

**Comment by relgisri** [comment]
so this example is not working anymore and therefore deprecated?

**Comment by rvaidya** [comment]
This plugin is now also incompatible with terraform 1.2+ because of this issue.

**Comment by rvaidya** [comment]
This module is deprecated by google_compute_router_nat: 

 https://www.terraform.io/docs/providers/google/r/compute_router_nat.html

**Comment by morgante** [comment]
Indeed, you can use this module to manage a Cloud NAT: https://github.com/terraform-google-modules/terraform-google-cloud-nat

**Comment by rvaidya** [comment]
> Indeed, you can use this module to manage a Cloud NAT: https://github.com/terraform-google-modules/terraform-google-cloud-nat

google_compute_router_nat is directly built into the official Terraform Google provider and it's pretty easy to set up.
