### ISSUE TITLE
Missing equals signs in map variable default

### ISSUE THREAD

**Issue by apparentlymart** [GoogleCloudPlatform/terraform-google-nat-gateway#18]
https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/blob/539a45389cb92ae01bc7ef2aa4912f96a5e4c0a7/variables.tf#L82-L139

Current versions of Terraform (as of 0.11) use an HCL parser that is very liberal in its distinctions between blocks, attributes, and expressions. A future version of Terraform will include a new HCL parser that permits use of arbitrary expressions directly as attribute values, rather than requiring expressions to always be interpolated into strings.

Unfortunately, making that improvement required resolving some ambiguity in the syntax that means that the new parser now distinguishes blocks from attributes so that it can tell the difference between a map expression and a child block. This means that the map members in the above variable default can no longer be parsed, since the parser believes them to be nested blocks which are not valid in this context:

```
Error: Missing key/value separator

  on .terraform/init-from-module/root/GoogleCloudPlatform-terraform-google-nat-gateway-539a453/variables.tf line 87:
  86:   default = {
  87:     us-west1 {

Expected an equals sign ("=") to mark the beginning of the item value.
```

Would you be open to updating these to use the idiomatic form with an equals sign, so that they'll parse as expected in the new parser once released?

```hcl
  default = {
    us-west1 = {
      zone = "us-west1-b"
    }
    # ...
  }
```

Thanks!

**Comment by danisla** [comment]
Fixed with #24
