### ISSUE TITLE
Default value for 'name' variable prevents route creation

### ISSUE THREAD

**Issue by tylrd** [GoogleCloudPlatform/terraform-google-nat-gateway#22]
The [default value](https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/blob/4d6fa0332163758395d3df09334433901c3348fc/variables.tf#L46) for the variable 'name' is an empty string. If a name is not provided to the module, the route that is attempted to be created is named "-nat-zone", which is an invalid name for a route. 

This issue surfaced by the addition of a '-' prefix to the route name in commit [here](https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/commit/b1b8f390620b6959e46114dde457d44d7d77bef4#diff-7a370d8342e7203b805911c92454f0f4R76).

Either the name variable needs to be a required variable or the generated name with an empty name needs to be a valid name for a route.

**Comment by danisla** [comment]
Fixed with #23
