### ISSUE TITLE
Security patches can disable net.ipv4.ip_forward

### ISSUE THREAD

**Issue by jackmurphy** [GoogleCloudPlatform/terraform-google-nat-gateway#35]
This morning an unattended upgrade ran on my egress nodes and upgraded the libprocps3 and procps packages. This caused my sysctl ip_forward setting to revert to disabled.

```
jmurphy@us-east1-d-egress-b310:~$ sudo sysctl -a | grep ip_forward
net.ipv4.ip_forward = 0
```

Uncommenting the `#net.ipv4.ip_forward=1` line in `/etc/sysctl.conf` seems to resolve the issue. I'm now able to manually update the libprocps3 and procps packages without interruption.

It seems like we should add the following to the nat-startup-script: 
```
sed -i= 's/^[# ]*net.ipv4.ip_forward=[[:digit:]]/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
```

Another option would be disabling automatic updates on these hosts completely, but that strikes me as pretty heavy handed.

**Comment by Pindar** [comment]
I ran into the exact same issue. Thank you @jackmurphy for providing a quick solution!

**Comment by Chnkr** [comment]
I ran into the exact same issue, thanks for the suggestion 👍

**Comment by dwdraju** [comment]
We had to face downtime on production because of this issue. Need to fix this issue asap and permanently. For now, I removed the nat completely and don't have gut to bring it back any time soon. Thanks.

**Comment by danisla** [comment]
@jackmurphy thanks for the quick suggested fix. That will work and preserve automatic patches. Will merge shortly.
