### ISSUE TITLE
Kubernetes nodes loose connection to the master after NAT setup

### ISSUE THREAD

**Issue by Chnkr** [GoogleCloudPlatform/terraform-google-nat-gateway#36]
I've ran into this issue earlier today, we've been running the NAT setup for about 2/3 weeks on a GKE cluster and earlier today all nodes started reporting as `notReady` and GKE reported they had not talked to the master for a few hours.

Removing the routes placed by the setup seems to rectify the issue and the nodes pop back up, any suggestions on what this could be?

**Comment by Pindar** [comment]
Hey @Chnkr, since I had the same symptom I can say that you should try the suggestions mentioned in #35 . For me it solved my GKE problems.
