### ISSUE TITLE
getting gcloud ssh working with a nat gateway ?

### ISSUE THREAD

**Issue by sandys** [GoogleCloudPlatform/terraform-google-nat-gateway#41]
hi,
is there a way we can configure the NAT gateway or routes in such a way that the browser ssh or gcloud compute ssh can still keep working while the outgoing traffic uses the NAT gateway ?

we are deploying kubernetes and spark using your scripts. We also want to ssh into our instances (for quick hacks) and more importantly - port forward so that we can use Zeppelin through the browser on our laptops. Its a little hard to get it to work with NAT gateways

**Comment by danisla** [comment]
Typically you need a bastion host to reach instances without an external IP address.

You can use a command like this to use the NAT gateway itself as a bastion and ssh into an instance in the same network (assuming your instance firewall rules allow it):

```
gcloud compute config-ssh
eval `ssh-agent $SHELL`
ssh-add ~/.ssh/google_compute_engine
BASTION=$(terraform output -module nat-zone-1 -json | jq -r '.instance.value')
REMOTE_HOST=$(terraform output -module mig1 -json | jq -r '.instances.value[0][0]')
SSH_USER=$(gcloud config get-value account)
gcloud compute ssh ${SSH_USER//@*}@${BASTION} --ssh-flag="-A" -- ssh ${REMOTE_HOST//*instances\//} -o StrictHostKeyChecking=no
```

Above is from the [ha-nat-gateway example](https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/tree/master/examples/ha-nat-gateway)

**Comment by sandys** [comment]
hi Dan,
thanks for taking the time to reply.

We have a dataproc cluster running behind the nat gateway. All outgoing
traffic of the dataproc cluster needs to be routed through the gateway.

Dataproc has a UI called Zeppelin running which we access using tunneling.
https://cloud.google.com/dataproc/docs/concepts/accessing/cluster-web-interfaces#create_an_ssh_tunnel

we are not able to figure out how to do this with your bastion (which is
also a nat gateway)

**Comment by danisla** [comment]
You can create a tunnel to your Zeppelin UI through the bastion using a command like the one below:

```
ZEPPELIN_IP=10.127.0.5
gcloud compute ssh${SSH_USER//@*}@${BASTION} --ssh-flag="-vv -N -D 1080 -L 8080:${ZEPPELIN_IP}:8080"
```

> Make sure you have a firewall rule that allows traffic from the bastion to your zeppelin instance!

This lets you access Zeppelin either from http://localhost:8080 or at http://ZEPPELIN_IP:8080 through the socks proxy on port 1080.
