### ISSUE TITLE
Add support for setting dest_range

### ISSUE THREAD

**Issue by tpoindessous** [GoogleCloudPlatform/terraform-google-nat-gateway#54]
Hi

we use this module and we were forced to fork it, because we wanted to set `dest_range` to a specific ip.

It would be great if we could use this module and set `dest_range` as a module's input.

Thanks !

**Comment by AndrewFarley** [comment]
That sounds like it could be a relatively simple PR, if you have already done the legwork, why don't you provide a PR for that?  Cheers!

**Comment by tpoindessous** [comment]
Hi

yes, it's true :)

I will do it in a few hours, for the moment, I send you the diff :) But I will do the PR.

Thanks ! 

[dest_range.diff.txt](https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway/files/2110856/dest_range.diff.txt)
