### ISSUE TITLE
Is this example of gke usable in a regional cluster?

### ISSUE THREAD

**Issue by vshimoda** [GoogleCloudPlatform/terraform-google-nat-gateway#60]
i created regional cluster with this GKE sample.
but, it failed to execute kubectl logs...

---
part of the error message
```
No SSH tunnels currently open. Were the targets able to accept an ssh-key for user 
```

**Comment by danisla** [comment]
Yes it works with regional clusters. With a regional GKE cluster, the endpoint is a load balancer across the master IPs and you need the actual master IPs for the NAT route.

Make sure you used the Master IP from the firewall rule like this:

```
MASTER_IP=$(gcloud compute firewall-rules describe ${NODE_TAG/-node/-ssh} --format='value(sourceRanges)')
```

**Comment by vshimoda** [comment]
Thank you! I found that the firewall rule was missing in the VPC created by me.
