### ISSUE TITLE
Usage of broken MIG version

### ISSUE THREAD

**Issue by Yanson** [GoogleCloudPlatform/terraform-google-nat-gateway#65]
Managed instance groups 1.1.9 is broken (see https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/issues/20).

Nat gateway 1.1.10 specifies mig-1.1.9 but nat gateway 1.1.9 does not specify mig version, hence mig-1.1.9 is picked up.

Maybe the mig version should be a variable to allow the client to choose non-broken version should this happen in future.

Either way, there needs to be a new version of nat-gateway that specifies mig-1.1.8 as it is currently unusable.

`module.nat-gateway.data.google_compute_zones.available: data.google_compute_zones.available: project: required field is not set`

**Comment by danisla** [comment]
This should be fixed now with 1.1.10 of the managed instance group module. Since it's also the latest, nat gateway 1.1.9 should pick up the latest mig version too.

**Comment by Yanson** [comment]
Updated to `1.1.11` which is working now. Closing.
