### ISSUE TITLE
Terraform apply fails when run from Windows

### ISSUE THREAD

**Issue by rvaidya** [GoogleCloudPlatform/terraform-google-nat-gateway#72]
My usage:

```
module "nat_cluster" {
  source     = "GoogleCloudPlatform/nat-gateway/google"
  region     = "us-central1"
  zone       = "us-central1-a"
  network    = "default"
  subnetwork = "default"
}
```

When I run terraform apply I get:

```
module.global.module.nat_cluster.module.nat_cluster.module.nat-gateway.google_compute_instance_group_manager.default (local-exec): Executing: ["sh" "-c" ":"]

Error: Error applying plan:

1 error(s) occurred:

* module.global.module.nat_cluster.module.nat_cluster.module.nat-gateway.google_compute_instance_group_manager.default: Error running command ':': exec: "sh": executable file not found in %PATH%. Output:
```

I think this is due to the usage of path.module

In my own terraform config, I haven't had any issues using relative paths when using file() - is path.module necessary here?

**Comment by danisla** [comment]
This is because the managed instance group module has a shell hook for create and destroy. The `sh` command doesn’t exist on Windows. It might work if you are running bash on windows.

**Comment by rvaidya** [comment]
Can the commands be skipped if left unset?  Otherwise it seems like this would work cross platform.

**Comment by rvaidya** [comment]
Is the extra interpreter bit "sh -c" required for local exec create?  It's not there for destroy and that's what's locking execution to non-Windows environments?

**Comment by danisla** [comment]
Yup that's the line that is breaking non unix platforms. I'll see if there is a more cross-platform workaround.
