### ISSUE TITLE
Zonal tag does not work

### ISSUE THREAD

**Issue by rvaidya** [GoogleCloudPlatform/terraform-google-nat-gateway#73]
```
resource "google_compute_route" "nat-gateway" {
  count                  = "${var.module_enabled ? 1 : 0}"
  name                   = "${var.name}nat-${var.zone == "" ? lookup(var.region_params["${var.region}"], "zone") : var.zone}"
  project                = "${var.project}"
  dest_range             = "${var.dest_range}"
  network                = "${data.google_compute_network.network.self_link}"
  next_hop_instance      = "${element(split("/", element(module.nat-gateway.instances[0], 0)), 10)}"
  next_hop_instance_zone = "${var.zone == "" ? lookup(var.region_params["${var.region}"], "zone") : var.zone}"
  tags                   = ["${compact(concat(list("${var.name}nat-${var.region}"), var.tags))}"]
  priority               = "${var.route_priority}"
}
```

The only source tag being created here is "${var.name}nat-${var.region}", there is no zonal tag being created.

**Comment by danisla** [comment]
Good point, what is your use case for the zonal tag?

**Comment by rvaidya** [comment]
My set of instances is small (all in one zone), and there is a non zero
cost to inter zone traffic.

**Comment by rvaidya** [comment]
I think it creates the gateway in us-central1-f by default looking at the zone map in variables, which would incur that nonzero cost if my resources are all in us-central1-a.

Don't know if it's important to officially support as the cost isn't very high but as it is right now the documentation / usage examples in the README are inconsistent with the outputs that are actually produced.

**Comment by danisla** [comment]
In your case I would say use the `zone` parameter to set the zone to `us-central1-a` the default zone map is just there for convenience.  

The README does need to be updated, thanks for pointing that out.

**Comment by rvaidya** [comment]
Switched over to using regional tag and all is working now, closing this issue.
