### ISSUE TITLE
Hanging on module.nat.nat-gateway.google_compute_instance_group_manager.default

### ISSUE THREAD

**Issue by huang-jy** [GoogleCloudPlatform/terraform-google-nat-gateway#83]
I am using this terraform definition to create a nat gateway (
```
variable tags {
  default = ["kubernetes"]
}

variable region {
  default = "europe-west2"
}

variable zone {
  default = "europe-west2-c"
}

variable network {
  default = "(vpc-network)"
}

variable subnetwork {
  default = "(vpc-subnetwork)"
}

variable k8s_external_ip {
  default = "(name of separately defined external ip)"
}

module "nat" {
  source = "github.com/GoogleCloudPlatform/terraform-google-nat-gateway"

  region = "${var.region}"

  zone            = "${var.zone}"
  tags            = ["${var.tags}"]
  network         = "${var.network}"
  subnetwork      = "${var.subnetwork}"
  ip_address_name = "${var.k8s_external_ip}"
}
```

I then use terraform plan and terraform apply and it gets stuck on creating 

module.nat.nat-gateway.google_compute_instance_group_manager.default

After 20 minutes it times out.

I'm not hitting any quotas and I can see the instance group with status "Instance is being verified", but it never proceeds beyond this...

![image](https://user-images.githubusercontent.com/2756283/44532019-08808a80-a6ea-11e8-8472-f831b24bd629.png)

Any ideas what is causing this?

**Comment by danisla** [comment]
I am seeing timeouts in cases where health checks are enabled on managed instance groups. The latest version of this module disables these health checks by setting the variable `autohealing_enabled=false`.

Do you still see the problem when using version 1.2.0 of the module?

```hcl
source  = "GoogleCloudPlatform/nat-gateway/google"
version = "1.2.0"
```

**Comment by huang-jy** [comment]
That one seems to be fine -- and I wiped my .terraform/modules and re-inited terraform to be sure.

**Comment by danisla** [comment]
Thanks. I'm going to close this for now, reopen or create a new issue if you are still having trouble.
