### ISSUE TITLE
Disallow SSH in created NAT instances in Private GKE?

### ISSUE THREAD

**Issue by cosmicnag** [GoogleCloudPlatform/terraform-google-nat-gateway#84]
I see that the NAT instances created by this module allows ssh by default (using the GKE HA example)... is there a way I can disable these when I consume this as a module ?

**Comment by danisla** [comment]
The underlying managed instance group module let’s you toggle the firewall rule creation using the [ssh_fw_rule](https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/blob/master/variables.tf#L284) variable. We could pass this through from the NAT module so you can disable it with a variable.

**Comment by jl74** [comment]
Would appreciate this fix.
